name: tickle_data
resolution: workspace
description: SQLite persistence implementation using Drift.
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.24.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0
  tickle_core:
    path: ../tickle_core

dev_dependencies:
  drift_dev: ^2.24.0
  build_runner: ^2.4.11
